In [2]:
import numpy as np
import pandas as pd

In [3]:
incident = pd.read_csv('week6.csv')
incident.head()

,ID,Incident_Type,Occurred_date_time,Officer_ID,Subject_ID,Subject_Race,Subject_Gender
0,2015UOF-0072-1204-3004,Level 2 - Use of Force,2015-01-19 15:00:00,1634,2984,White,Male
1,2015UOF-1321-1306-5300,Level 2 - Use of Force,2015-08-03 15:30:00,1615,5261,White,Male
2,2020UOF-1310-1097-23017,Level 2 - Use of Force,2020-07-19 15:35:00,1672,23898,Nat Hawaiian/Oth Pac Islander,Male
3,2022UOF-1269-2902-29489,Level 2 - Use of Force,2022-11-10 06:29:00,5708,30362,White,Female

In [4]:
incident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  4 non-null      object
 1   Incident_Type       4 non-null      object
 2   Occurred_date_time  4 non-null      object
 3   Officer_ID          4 non-null      int64
 4   Subject_ID          4 non-null      int64
 5   Subject_Race        4 non-null      object
 6   Subject_Gender      4 non-null      object
dtypes: int64(2), object(5)
memory usage: 356.0+ bytes

In [8]:
incident.describe(include="all")

,ID,Incident_Type,Occurred_date_time,Officer_ID,Subject_ID,Subject_Race,Subject_Gender
count,4,4,4,4.000000,4.000000,4,4
unique,4,1,4,NaN,NaN,2,2
top,2015UOF-0072-1204-3004,Level 2 - Use of Force,2015-01-19 15:00:00,NaN,NaN,White,Male
freq,1,4,1,NaN,NaN,3,3
mean,NaN,NaN,NaN,2657.250000,15626.250000,NaN,NaN
std,NaN,NaN,NaN,2033.971382,13574.842771,NaN,NaN
min,NaN,NaN,NaN,1615.000000,2984.000000,NaN,NaN
25%,NaN,NaN,NaN,1629.250000,4691.750000,NaN,NaN
50%,NaN,NaN,NaN,1653.000000,14579.500000,NaN,NaN
75%,NaN,NaN,NaN,2681.000000,25514.000000,NaN,NaN
max,NaN,NaN,NaN,5708.000000,30362.000000,NaN,NaN

In [9]:
incident.isnull().sum()

ID                    0
Incident_Type         0
Occurred_date_time    0
Officer_ID            0
Subject_ID            0
Subject_Race          0
Subject_Gender        0
dtype: int64

In [10]:
# Drop rows where critical data is missing

In [12]:
clean = incident.copy()

clean = incident.copy()

critical_cols = ["ID","Occurred_date_time"]
before = clean.shape[0] # returns rows
clean = clean.dropna(subset = critical_cols)
after = clean.shape[0]

print("Rows before:", before)
print("Rows after:", after)
clean.head()

In [11]:
# Fill missing values in other columns using a reasonable strategy (for example: median, mode, or "Unknown")

clean = clean.fillna(value = "Unknown")
clean.head()

We showed the above code as examples for what we would do if we had NaN data. Hwoever, our data did not have any NaN data, so we can proceed with the next steps

In [ ]:
# Remove leading/trailing spaces

# Standardize text (for example: convert names or categories to consistent casing)

In [13]:
# Strip spaces from ALL text columns
obj_cols = clean.select_dtypes(include=["object"]).columns.tolist()
for c in obj_cols:
    clean[c] = clean[c].astype(str).str.strip()
    
clean.head()

,ID,Incident_Type,Occurred_date_time,Officer_ID,Subject_ID,Subject_Race,Subject_Gender
0,2015UOF-0072-1204-3004,Level 2 - Use of Force,2015-01-19 15:00:00,1634,2984,White,Male
1,2015UOF-1321-1306-5300,Level 2 - Use of Force,2015-08-03 15:30:00,1615,5261,White,Male
2,2020UOF-1310-1097-23017,Level 2 - Use of Force,2020-07-19 15:35:00,1672,23898,Nat Hawaiian/Oth Pac Islander,Male
3,2022UOF-1269-2902-29489,Level 2 - Use of Force,2022-11-10 06:29:00,5708,30362,White,Female

# Standardize city to Title Case (example choice)
if "subject_race" in clean.columns:
    clean["patient_name"] = clean["patient_name"].str.title()
if "subject_gender" in clean.columns:
    clean["clinic"] = clean["clinic"].str.title()

In [14]:
# Convert date columns to datetime objects (Only showing as an example)
if "Occurred_date_time" in clean.columns:
    clean["Occurred_date_time"] = pd.to_datetime(clean["Occurred_date_time"], errors="coerce")

clean[["Occurred_date_time"]].head() if "Occurred_date_time" in clean.columns else clean.head()

   Occurred_date_time
0 2015-01-19 15:00:00
1 2015-08-03 15:30:00
2 2020-07-19 15:35:00
3 2022-11-10 06:29:00

In [16]:
clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  4 non-null      object
 1   Incident_Type       4 non-null      object
 2   Occurred_date_time  4 non-null      datetime64[ns]
 3   Officer_ID          4 non-null      int64
 4   Subject_ID          4 non-null      int64
 5   Subject_Race        4 non-null      object
 6   Subject_Gender      4 non-null      object
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 356.0+ bytes

In [20]:
# Rename Occurred_date_time to Date_Time

In [21]:
clean = clean.rename(columns={"Occurred_date_time": "Date_Time"})
clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              4 non-null      object
 1   Incident_Type   4 non-null      object
 2   Date_Time       4 non-null      datetime64[ns]
 3   Officer_ID      4 non-null      int64
 4   Subject_ID      4 non-null      int64
 5   Subject_Race    4 non-null      object
 6   Subject_Gender  4 non-null      object
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 356.0+ bytes

In [22]:
clean.head()

,ID,Incident_Type,Date_Time,Officer_ID,Subject_ID,Subject_Race,Subject_Gender
0,2015UOF-0072-1204-3004,Level 2 - Use of Force,2015-01-19 15:00:00,1634,2984,White,Male
1,2015UOF-1321-1306-5300,Level 2 - Use of Force,2015-08-03 15:30:00,1615,5261,White,Male
2,2020UOF-1310-1097-23017,Level 2 - Use of Force,2020-07-19 15:35:00,1672,23898,Nat Hawaiian/Oth Pac Islander,Male
3,2022UOF-1269-2902-29489,Level 2 - Use of Force,2022-11-10 06:29:00,5708,30362,White,Female

In [27]:
#Added 
if "Date_Time" in clean.columns:
    clean["Year"] = clean["Date_Time"].dt.year
    clean["Month"] = clean["Date_Time"].dt.month
clean.head()

,ID,Incident_Type,Date_Time,Officer_ID,Subject_ID,Subject_Race,Subject_Gender,Year,Month
0,2015UOF-0072-1204-3004,Level 2 - Use of Force,2015-01-19 15:00:00,1634,2984,White,Male,2015,1
1,2015UOF-1321-1306-5300,Level 2 - Use of Force,2015-08-03 15:30:00,1615,5261,White,Male,2015,8
2,2020UOF-1310-1097-23017,Level 2 - Use of Force,2020-07-19 15:35:00,1672,23898,Nat Hawaiian/Oth Pac Islander,Male,2020,7
3,2022UOF-1269-2902-29489,Level 2 - Use of Force,2022-11-10 06:29:00,5708,30362,White,Female,2022,11

In [28]:
clean.to_csv("cleaned_data.csv", index=False)
print("Saved: cleaned_data.csv")
clean.head()

Saved: cleaned_data.csv

,ID,Incident_Type,Date_Time,Officer_ID,Subject_ID,Subject_Race,Subject_Gender,Year,Month
0,2015UOF-0072-1204-3004,Level 2 - Use of Force,2015-01-19 15:00:00,1634,2984,White,Male,2015,1
1,2015UOF-1321-1306-5300,Level 2 - Use of Force,2015-08-03 15:30:00,1615,5261,White,Male,2015,8
2,2020UOF-1310-1097-23017,Level 2 - Use of Force,2020-07-19 15:35:00,1672,23898,Nat Hawaiian/Oth Pac Islander,Male,2020,7
3,2022UOF-1269-2902-29489,Level 2 - Use of Force,2022-11-10 06:29:00,5708,30362,White,Female,2022,11